config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'welcome', to: 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :invitations do
    resources :guests, only: [:new, :create], controller: 'invitations/guests'
  end

  resources :guests
  resources :invitation_imports
  resources :tables

  namespace :api do
    resources :invitations, only: :show, param: :rsvp_code
    resources :rsvps, only: :create
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  ENTREE_CHOICES = %w(salmon surf_n_turf duck veg).freeze
  ENTREE_NAMES = {
    salmon: 'Atlantic Salmon',
    surf_n_turf: 'Surf & Turf',
    duck: 'Roasted Duck',
    veg: 'Vegetarian'
  }

  belongs_to :invitation
  belongs_to :table, optional: true

  validates :entree_selection, inclusion: { in: ENTREE_CHOICES }, if: -> { accepted_at.present? }

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :declined, -> { where.not(declined_at: nil) }
  scope :outstanding, -> { where(accepted_at: nil, declined_at: nil) }
  scope :not_declined, -> { where(declined_at: nil) }

  self.per_page = 200

  def self.entree_options
    ENTREE_CHOICES.map do |value|
      [ENTREE_NAMES[value.to_sym], value]
    end.freeze
  end

  def accept!(params)
    update!(accepted_at: Time.zone.now, declined_at: nil, name: params[:name], entree_selection: params[:entree_selection])
  end

  def decline!
    update!(declined_at: Time.zone.now, accepted_at: nil, entree_selection: nil)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests_grid = GuestsGrid.new(index_params) do |scope|
      scope.page(params[:page])
    end

    respond_to do |format|
      format.html
      format.csv { send_data @guests_grid.to_csv, filename: "guests-#{Date.today}.csv" }
    end
  end

  def edit
    @guest = Guest.find params[:id]
  end

  def update
    @guest = Guest.find params[:id]

    if @guest.update update_params
      redirect_to invitation_path(@guest.invitation)
    else
      render :edit
    end
  end

  private

  def update_params
    params.fetch(:guest, {}).permit(:name, :table_id)
  end

  def index_params
    params.fetch(:guests_grid, {}).permit(:name, :entree_selection, :accepted, :declined, :outstanding, :order, :ascending, :descending)
  end
end

app/controllers/invitations/guests_controller.rb
class Invitations::GuestsController < ApplicationController
  def new
    @invitation = Invitation.find params[:invitation_id]
  end

  def create
    @invitation = Invitation.find params[:invitation_id]
    guest = @invitation.guests.build create_params

    if guest.save
      redirect_to invitation_path(@invitation)
    else
      flash[:error] = 'Guest creation failed'
      render :new
    end
  end

  private

  def create_params
    params.fetch(:guest, {}).permit(:name)
  end
end

app/views/guests/_guest_table.html.erb
<table>
  <thead>
    <tr>
      <td></td>
      <td>Name</td>
      <td>Accepted at</td>
      <td>Declined at</td>
      <td>Entree Selection</td>
    </tr>
  </thead>
  <tbody>
    <% guests.each do |guest| %>
      <tr>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td>
          <% if guest.name.present? %>
            <%= guest.name %>
          <% else %>
            (guest)
          <% end %>
        </td>
        <td><%= guest.accepted_at %></td>
        <td><%= guest.declined_at %></td>
        <td><%= guest.entree_selection %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/guests/edit.html.erb
<h2>Edit guest for invitation <%= @guest.invitation.rsvp_code %> (<%= @guest.invitation.addressee %>)</h2>
<%= simple_form_for @guest, url: guest_path(@guest), method: :put do |f| %>
  <%= f.input :name %>
  <%= f.association :table, label_method: :full_name, value_method: :id %>
  <%= f.submit %>
<% end %>

app/views/guests/index.html.erb
<h1>Guests</h1>

<%= datagrid_form_for @guests_grid, url: guests_path %>

<p>Total guests: <%= @guests_grid.assets.total_entries %></p>

<p><%= link_to 'Download CSV', format: :csv %></p>

<%= datagrid_table @guests_grid %>
<%= will_paginate @guests_grid.assets %>