config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'welcome', to: 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :invitations do
    resources :guests, only: [:new, :create], controller: 'invitations/guests'
  end

  resources :guests
  resources :invitation_imports
  resources :tables

  namespace :api do
    resources :invitations, only: :show, param: :rsvp_code
    resources :rsvps, only: :create
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  has_many :guests

  validates :rsvp_code, :addressee, :address_line_1, :city, :zip, presence: true
  validates :rsvp_code, uniqueness: true

  validates :accepted_at, absence: true, if: -> { declined_at.present? }
  validates :declined_at, absence: true, if: -> { accepted_at.present? }

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :declined, -> { where.not(declined_at: nil) }
  scope :outstanding, -> { where(accepted_at: nil, declined_at: nil) }

  before_validation :set_rsvp_code, if: -> { rsvp_code.nil? }

  self.per_page = 100

  def address_to_s
    lines = []
    lines << address_line_1
    lines << address_line_2 if address_line_2.present?
    city_state = []
    city_state << city
    city_state << state if state.present?
    city_state << country if country.present?
    last_line = [city_state.join(", "), zip].join(" ")
    lines << last_line
    lines.join("\n")
  end

  def accept!(comment, guest_params)
    transaction do
      update!(accepted_at: Time.zone.now, declined_at: nil, rsvp_comment: comment)
      guests.each do |guest|
        response = guest_params.find { |g| g[:id].to_i == guest.id }
        if response.present?
          guest.accept! response
        else
          guest.decline!
        end
      end
    end
  end

  def decline!(comment)
    transaction do
      update!(declined_at: Time.zone.now, accepted_at: nil, rsvp_comment: comment)
      guests.each(&:decline!)
    end
  end

  def accepted?
    accepted_at.present?
  end

  private

  def set_rsvp_code
    existing_codes = self.class.pluck(:rsvp_code)
    self.rsvp_code = generate_rsvp_code

    while existing_codes.include? rsvp_code
      self.rsvp_code = generate_rsvp_code
    end
  end

  def generate_rsvp_code
    (0..1).map { code_letters[rand(code_letters.length)] }.concat([rand(2..9)]).join
  end

  def code_letters
    ('a'..'z').reject { |x| x == 'o' }
  end
end

app/controllers/api/invitations_controller.rb
class Api::InvitationsController < ApiController
  def show
    @invitation = Invitation.find_by! rsvp_code: params[:rsvp_code]
  end
end

app/controllers/app/invitations_controller.rb
class App::InvitationsController < ApplicationController
  def index
    @invitations = Invitation.all
  end

  def show
    @invitation = Invitation.find params[:id]
  end
end

app/controllers/invitations/guests_controller.rb
class Invitations::GuestsController < ApplicationController
  def new
    @invitation = Invitation.find params[:invitation_id]
  end

  def create
    @invitation = Invitation.find params[:invitation_id]
    guest = @invitation.guests.build create_params

    if guest.save
      redirect_to invitation_path(@invitation)
    else
      flash[:error] = 'Guest creation failed'
      render :new
    end
  end

  private

  def create_params
    params.fetch(:guest, {}).permit(:name)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations_grid = InvitationsGrid.new(index_params) do |scope|
      scope.page(params[:page])
    end
  end

  def show
    @invitation = Invitation.find params[:id]
  end

  def create
    @invitation = Invitation.new
    @invitation.assign_attributes create_params

    if @invitation.save
      redirect_to invitations_path
    else
      render :new
    end
  end

  private

  def create_params
    params.fetch(:invitation, {}).permit(:addressee, :address_line_1, :address_line_2, :city, :state, :zip, :country)
  end

  def index_params
    params.fetch(:invitations_grid, {}).permit(:rsvp_code, :addressee, :accepted, :declined, :outstanding, :descending, :ascending, :order)
  end
end

app/views/invitations/index.html.erb
<h1>Invitations - <%= link_to 'New Invitation', new_invitation_path %></h1>
<p><%= link_to 'Guests', guests_path %></p>
<p><%= link_to 'Tables', tables_path %></p>

<%= datagrid_form_for @invitations_grid, url: invitations_path %>

<p>Total invitations: <%= @invitations_grid.assets.total_entries %></p>
<p>Total guests: <%= @invitations_grid.assets.sum { |i| i.guests.not_declined.count } %></p>

<%= datagrid_table @invitations_grid %>
<%= will_paginate @invitations_grid.assets %>

app/views/invitations/new.html.erb
<h2>New Invitation</h2>
<%= simple_form_for :invitation, url: invitations_path, method: :post do |f| %>
  <%= f.input :addressee %>
  <%= f.input :address_line_1 %>
  <%= f.input :address_line_2 %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :country, as: :text %>
  <%= f.input :zip %>
  <%= f.submit %>
<% end %>

app/views/invitations/show.html.erb
<p><%= link_to 'Back', invitations_path %></p>
<h1>Invitation <%= @invitation.rsvp_code %></h1>

<p><%= @invitation.addressee %></p>
<p><%= @invitation.address_to_s %></p>

<hr></hr>

<p>Sent at: <%= @invitation.sent_at %></p>
<% if @invitation.accepted_at.present? %>
  <p>Accepted at: <%= @invitation.accepted_at %></p>
<% elsif @invitation.declined_at.present? %>
  <p>Declined at: <%= @invitation.declined_at %></p>
<% end %>

<% if @invitation.rsvp_comment.present? %>
  <p>RSVP Comment: <%= @invitation.rsvp_comment %></p>
<% end %>

<h2>Guests - <%= link_to 'New Guest', new_invitation_guest_path(@invitation) %></h2>

<%= render 'guests/guest_table', guests: @invitation.guests %>