config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'welcome', to: 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :invitations do
    resources :guests, only: [:new, :create], controller: 'invitations/guests'
  end

  resources :guests
  resources :invitation_imports
  resources :tables

  namespace :api do
    resources :invitations, only: :show, param: :rsvp_code
    resources :rsvps, only: :create
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.order(:number)
  end

  def edit
    @table = Table.find params[:id]
  end

  def update
    @table = Table.find params[:id]

    if @table.update create_params
      redirect_to tables_path
    else
      render :edit
    end
  end

  def create
    @table = Table.new
    @table.assign_attributes create_params

    if @table.save
      redirect_to tables_path
    else
      render :new
    end
  end

  def destroy
    @table = Table.find params[:id]
    @table.destroy!
    redirect_to tables_path
  end

  private

  def create_params
    params.fetch(:table, {}).permit(:number, :description)
  end
end

app/views/tables/edit.html.erb
<h2>Edit Table</h2>
<%= simple_form_for @table, url: table_path(@table), method: :put do |f| %>
  <%= f.input :number %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/tables/index.html.erb
<h1>Tables - <%= link_to 'New Table', new_table_path %></h1>

<% @tables.each do |table| %>
  <h2><%= table.full_name %> (<%= table.guests.count %> guests) (<%= table.entree_counts_display %>)</h2>

  <% table.guests.to_a.group_by(&:invitation).values.flatten.each do |guest| %>
    <p><%= guest.name %> - <%= guest.entree_selection %></p>
  <% end %>


  <p><%= link_to 'Edit', edit_table_path(table) %></p>
  <p><%= link_to 'Delete', table_path(table), method: :delete, data: { confirm: 'Are you sure?' } %></p>

  <hr></hr>
<% end %>

app/views/tables/new.html.erb
<h2>New Table</h2>
<%= simple_form_for :table, url: tables_path, method: :post do |f| %>
  <%= f.input :number %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>